# -*- coding: utf-8 -*-
{
    "name": "PetSpot Campaign Rewards",
    "version": "19.0.1.2.0",
    "category": "Marketing",
    "summary": "Facebook Knowledge Quest — quizzes, CRM leads, discount codes, WhatsApp rewards",
    "author": "Sabry Youssef",
    "license": "LGPL-3",
    "depends": [
        "website",
        "survey",
        "website_slides",
        "website_slides_survey",
        "website_knowledge",
        "loyalty",
        "sale_loyalty",
        "pos_loyalty",
        "survey_crm",
        "crm",
        "knowledge",
        "social_media_connector",
        "integration_bridge_core",
        "petspot_clinic_portal",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/crm_tag_data.xml",
        "data/loyalty_program_data.xml",
        "data/mail_template_data.xml",
        "data/campaign_data.xml",
        "views/petspot_campaign_views.xml",
        "views/survey_views.xml",
        "views/res_config_settings_views.xml",
        "views/website_templates.xml",
        "views/survey_website_templates.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "petspot_campaign_rewards/static/src/scss/campaign_survey.scss",
        ],
        "survey.survey_assets": [
            "petspot_campaign_rewards/static/src/scss/campaign_survey.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
