# -*- coding: utf-8 -*-
{
    "name": "Development Session Hub",
    "version": "19.0.9.1.0",
    "category": "Productivity",
    "summary": "Dev Hub compatibility meta-module (installs full modular stack)",
    "description": "Compatibility bridge preserving Dev Hub XML IDs, menus, and seed data.",
    "author": "Sabry Youssef",
    "license": "LGPL-3",
    "depends": [
        "devhub_core",
        "devhub_work",
        "devhub_analysis",
        "devhub_plan",
        "devhub_approval",
        "devhub_session",
        "devhub_execution",
        "devhub_outbox",
        "devhub_generation",
        "devhub_git",
        "devhub_github",
        "devhub_deploy",
        "devhub_odoo_runtime",
        "devhub_infrastructure",
        "devhub_openproject",
        "devhub_code_analysis",
        "devhub_whatsapp",
        "devhub_workflow",
    ],
    "data": [
        "security/dev_session_hub_rules.xml",
        "security/ir.model.access.csv",
        "data/dev_session_hub_seed.xml",
        "views/dev_session_hub_menus.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
