# -*- coding: utf-8 -*-
"""Export partners and partner tags from a PostgreSQL Odoo DB into module demo XML files."""

from __future__ import annotations

import argparse
import datetime as dt
import html
from pathlib import Path

import psycopg2


def normalize_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, dict):
        if "en_US" in value and value["en_US"]:
            return str(value["en_US"])
        for v in value.values():
            if v:
                return str(v)
        return ""
    return str(value)


def clean_xml_text(value: str) -> str:
    # XML 1.0 allowed chars: tab, LF, CR, and Unicode ranges excluding control chars.
    return "".join(
        ch
        for ch in value
        if ch in ("\t", "\n", "\r") or ord(ch) >= 0x20
    )


def xml_escape(value: str) -> str:
    return html.escape(clean_xml_text(normalize_text(value)), quote=True)


def field_line(name: str, value: str | None) -> str:
    if value in (None, ""):
        return ""
    return f'            <field name="{name}">{xml_escape(value)}</field>'


def bool_line(name: str, value: bool | None) -> str:
    if value is None:
        return ""
    return f'            <field name="{name}" eval="{str(bool(value))}"/>'


def export(db_name: str, host: str, port: int, user: str, password: str, out_dir: Path) -> tuple[int, int]:
    out_dir.mkdir(parents=True, exist_ok=True)

    conn = psycopg2.connect(dbname=db_name, host=host, port=port, user=user, password=password)
    cur = conn.cursor()

    cur.execute(
        """
        SELECT res_id, module || '.' || name
        FROM ir_model_data
        WHERE module = 'base' AND model = 'res.country'
        """
    )
    country_xmlid_by_id = {row[0]: row[1] for row in cur.fetchall()}

    cur.execute(
        """
        SELECT res_id, module || '.' || name
        FROM ir_model_data
        WHERE module = 'base' AND model = 'res.country.state'
        """
    )
    state_xmlid_by_id = {row[0]: row[1] for row in cur.fetchall()}

    cur.execute(
        """
        SELECT id, name, color, active
        FROM res_partner_category
        ORDER BY id
        """
    )
    categories = cur.fetchall()

    category_xml = [
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
        "<odoo>",
        "    <data noupdate=\"1\">",
    ]
    for cat_id, name, color, active in categories:
        xmlid = f"odoo_partner_category_{cat_id}"
        category_xml.append(f'        <record id="{xmlid}" model="res.partner.category">')
        category_xml.append(f"            <field name=\"name\">{xml_escape(name or '')}</field>")
        if color is not None:
            category_xml.append(f"            <field name=\"color\">{int(color)}</field>")
        if active is not None:
            category_xml.append(f"            <field name=\"active\" eval=\"{str(bool(active))}\"/>")
        category_xml.append("        </record>")
    category_xml.extend(["    </data>", "</odoo>", ""])

    category_path = out_dir / "res_partner_category_demo.xml"
    category_path.write_text("\n".join(category_xml), encoding="utf-8")

    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'res_partner'
        """
    )
    partner_columns = {row[0] for row in cur.fetchall()}

    requested_columns = [
        "id",
        "name",
        "is_company",
        "type",
        "active",
        "email",
        "phone",
        "mobile",
        "street",
        "street2",
        "zip",
        "city",
        "vat",
        "website",
        "lang",
        "comment",
        "function",
        "parent_id",
        "country_id",
        "state_id",
    ]
    selected_columns = [col for col in requested_columns if col in partner_columns]
    cur.execute(
        f"SELECT {', '.join(selected_columns)} FROM res_partner ORDER BY id"
    )
    partners = cur.fetchall()

    cur.execute(
        """
        SELECT partner_id, category_id
        FROM res_partner_res_partner_category_rel
        """
    )
    partner_tags: dict[int, list[int]] = {}
    for partner_id, category_id in cur.fetchall():
        partner_tags.setdefault(partner_id, []).append(category_id)

    ts = dt.datetime.utcnow().isoformat() + "Z"
    partner_xml = [
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
        "<odoo>",
        "    <!-- Generated by tools/export_partners.py -->",
        f"    <!-- Source DB: {xml_escape(db_name)} at {xml_escape(ts)} -->",
        "    <data noupdate=\"1\">",
    ]

    for row in partners:
        rec = dict(zip(selected_columns, row))
        partner_id = rec.get("id")
        name = rec.get("name")
        is_company = rec.get("is_company")
        ptype = rec.get("type")
        active = rec.get("active")
        email = rec.get("email")
        phone = rec.get("phone")
        mobile = rec.get("mobile")
        street = rec.get("street")
        street2 = rec.get("street2")
        zip_code = rec.get("zip")
        city = rec.get("city")
        vat = rec.get("vat")
        website = rec.get("website")
        lang = rec.get("lang")
        comment = rec.get("comment")
        function = rec.get("function")
        parent_id = rec.get("parent_id")
        country_id = rec.get("country_id")
        state_id = rec.get("state_id")

        xmlid = f"odoo_partner_{partner_id}"
        partner_xml.append(f'        <record id="{xmlid}" model="res.partner">')

        lines = [
            field_line("name", name),
            bool_line("is_company", is_company),
            field_line("type", ptype),
            bool_line("active", active),
            field_line("email", email),
            field_line("phone", phone),
            field_line("mobile", mobile),
            field_line("street", street),
            field_line("street2", street2),
            field_line("zip", zip_code),
            field_line("city", city),
            field_line("vat", vat),
            field_line("website", website),
            field_line("lang", lang),
            field_line("function", function),
            field_line("comment", comment),
        ]
        if parent_id:
            lines.append(f'            <field name="parent_id" ref="odoo_partners.odoo_partner_{int(parent_id)}"/>')

        country_xmlid = country_xmlid_by_id.get(country_id)
        if country_xmlid:
            lines.append(f'            <field name="country_id" ref="{country_xmlid}"/>')

        state_xmlid = state_xmlid_by_id.get(state_id)
        if state_xmlid:
            lines.append(f'            <field name="state_id" ref="{state_xmlid}"/>')

        tag_ids = partner_tags.get(partner_id, [])
        if tag_ids:
            refs = ", ".join([f"ref('odoo_partners.odoo_partner_category_{int(cid)}')" for cid in sorted(set(tag_ids))])
            lines.append(f'            <field name="category_id" eval="[(6, 0, [{refs}])]"/>')

        for line in lines:
            if line:
                partner_xml.append(line)

        partner_xml.append("        </record>")

    partner_xml.extend(["    </data>", "</odoo>", ""])

    partner_path = out_dir / "res_partner_demo.xml"
    partner_path.write_text("\n".join(partner_xml), encoding="utf-8")

    cur.close()
    conn.close()
    return len(categories), len(partners)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export Odoo partners into module demo XML")
    parser.add_argument("--db", required=True, help="Database name")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=5432)
    parser.add_argument("--user", default="odoo19")
    parser.add_argument("--password", default="odoo19")
    parser.add_argument("--out", required=True, help="Output demo directory path")
    args = parser.parse_args()

    categories_count, partners_count = export(
        db_name=args.db,
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        out_dir=Path(args.out),
    )
    print(f"Exported {categories_count} categories and {partners_count} partners to {args.out}")
