from . import pet_species
from . import pet_breed
from . import pet_pet
from . import pet_weight
from . import pet_vaccine
from . import pet_vaccination
from . import pet_medical_visit
from . import pet_medical_visit_line
from . import pet_exam_price_config
from . import pet_medical_diagnostic_report
from . import pet_kennel
from . import pet_boarding
from . import pet_appointment
from . import pet_appointment_inventory
from . import pet_appointment_service_line
from . import sale_order
from . import account_move
from . import account_payment_register
from . import pet_billing_integrity_issue
from . import hr_employee
from . import pet_grooming
from . import pet_training
from . import pet_diet
from . import pet_notification
from . import pet_settings
from . import pet_help
