# -*- coding: utf-8 -*-
{
    "name": "LinkedIn Connector",
    "version": "19.0.2.16.1",
    "category": "Marketing",
    "summary": "Full LinkedIn management: posts, schedule, feed, jobs, resumes, messages",
    "author": "Sabry Youssef, Resume project",
    "author_email": "vendorah2@gmail.com, abhorya@gmail.com",
    "website": "https://github.com/sabryyoussef",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail", "base_setup"],
    "data": [
        "security/linkedin_security.xml",
        "security/ir.model.access.csv",
        "security/linkedin_bulk_wizard_access.xml",
        "data/ir_config_parameter_data.xml",
        "data/ir_cron_data.xml",
        "data/ats_source_data.xml",
        "views/linkedin_post_views.xml",
        "views/linkedin_stream_post_views.xml",
        "views/linkedin_job_views.xml",
        "views/linkedin_cv_version_views.xml",
        "views/linkedin_job_application_views.xml",
        "views/linkedin_resume_views.xml",
        "views/linkedin_message_views.xml",
        "views/linkedin_account_views.xml",
        "views/linkedin_bulk_wizard_views.xml",
        "views/linkedin_settings_views.xml",
        "views/linkedin_orchestrator_views.xml",
        "views/linkedin_caught_jobs_dashboard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "linkedin_connector/static/src/caught_jobs_dashboard/caught_jobs_dashboard.css",
            "linkedin_connector/static/src/caught_jobs_dashboard/caught_jobs_dashboard.js",
            "linkedin_connector/static/src/caught_jobs_dashboard/caught_jobs_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
}
