# -*- coding: utf-8 -*-
{
    "name": "PetSpot Vendor Sell-Through",
    "version": "19.0.1.4.3",
    "category": "Accounting/Purchase",
    "summary": "Track sold quantities per Vendor Bill and suggest cost-based partial payments",
    "depends": [
        "account",
        "accountant",
        "purchase_stock",
        "sale_stock",
        "stock",
        "mail",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/sell_through_rules.xml",
        "data/ir_cron_data.xml",
        "views/layer_views.xml",
        "views/allocation_views.xml",
        "views/account_move_views.xml",
        "views/supplier_dashboard_views.xml",
        "wizard/legacy_wizard_views.xml",
        "wizard/payment_wizard_views.xml",
        "wizard/rebuild_wizard_views.xml",
        "wizard/multi_payment_wizard_views.xml",
        "wizard/invoice_backfill_wizard_views.xml",
        "views/menus.xml",
        "data/ir_config_parameter_data.xml",
    ],
    "installable": True,
    "application": False,
    "author": "PetSpot",
    "license": "LGPL-3",
}
