# -*- coding: utf-8 -*-
{
    "name": "PetSpot Vet Shop",
    "summary": "PetSpot Vetution-style shop UX — original PetSpot branding, native Odoo pricing/cart",
    "version": "19.0.1.0.0",
    "category": "Website/Website",
    "author": "Sabry Youssef",
    "license": "LGPL-3",
    "depends": [
        "website_sale",
        "website_sale_stock",
        "website_sale_wishlist",
        "website_sale_stock_wishlist",
        "website_sale_autocomplete",
        "vetution_import",
        "vetution_supplier",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/disable_vetution_import_presentation.xml",
        "data/shop_hero_data.xml",
        "views/shop_layout_templates.xml",
        "views/sidebar_templates.xml",
        "views/product_card_templates.xml",
        "views/search_templates.xml",
        "views/website_sale_templates.xml",
        "views/product_template_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "petspot_vet_shop/static/src/scss/petspot_shop.scss",
            "petspot_vet_shop/static/src/scss/product_card.scss",
            "petspot_vet_shop/static/src/scss/sidebar.scss",
            "petspot_vet_shop/static/src/scss/responsive.scss",
            "petspot_vet_shop/static/src/js/shop_variant_selector.js",
            "petspot_vet_shop/static/src/js/shop_search.js",
            "petspot_vet_shop/static/src/js/shop_filters.js",
            "petspot_vet_shop/static/src/js/shop_cart.js",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
}
